
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import { BuildingConfig, BuildingType, Upgrade, Stock, Policy } from './types';

// Configurações Globais do Mapa
export const GRID_SIZE = 15; // Tamanho da grade (15x15 tiles)

// Configurações de Gameplay
// 1m 30s = 90000ms
export const TICK_RATE_MS = 90000; 
export const INITIAL_COOKIES = 1500; // Quantidade inicial de Cookies (Dinheiro)

/**
 * Definição de todos os prédios e suas propriedades.
 * Contém custo, geração de recursos, requisitos de desbloqueio e bônus.
 * 
 * NOTA: Todos os textos de exibição estão em Português do Brasil.
 */
export const BUILDINGS: Record<BuildingType, BuildingConfig> = {
  [BuildingType.None]: {
    type: BuildingType.None,
    cost: 0,
    name: 'Demolir',
    description: 'Limpar terreno para novas obras',
    color: '#ef4444', 
    emoji: '❌',
    popGen: 0,
    cookieGen: 0,
    unlockPop: 0,
    energyDelta: 0
  },
  [BuildingType.Road]: {
    type: BuildingType.Road,
    cost: 5,
    name: 'Estrada',
    description: 'Conecta áreas e melhora o transporte',
    color: '#374151',
    emoji: '🛣️',
    popGen: 0,
    cookieGen: 0,
    unlockPop: 0,
    energyDelta: 0,
    satisfactionBonus: { type: 'transport', amount: 2 }
  },
  [BuildingType.Residential]: {
    type: BuildingType.Residential,
    cost: 50,
    name: 'Residência',
    description: 'Lar para novos moradores (+3 Hab)',
    color: '#f87171', 
    emoji: '🏠',
    // Zerado para focar no crescimento instantâneo (+3 ao construir) e orgânico (satisfação)
    popGen: 0, 
    cookieGen: 5, 
    unlockPop: 0,
    energyDelta: -1, 
  },
  [BuildingType.Commercial]: {
    type: BuildingType.Commercial,
    cost: 150,
    name: 'Mercado',
    description: 'Gera renda com comércio (+15 Cookies)',
    color: '#60a5fa', 
    emoji: '🏪',
    popGen: 0,
    cookieGen: 15,
    unlockPop: 20,
    energyDelta: -2,
  },
  [BuildingType.Industrial]: {
    type: BuildingType.Industrial,
    cost: 300,
    name: 'Fábrica Tech',
    description: 'Alta produção de Cookies (+40 Cookies)',
    color: '#facc15', 
    emoji: '🏭',
    popGen: 0,
    cookieGen: 40,
    unlockPop: 50,
    energyDelta: -5,
  },
  [BuildingType.Park]: {
    type: BuildingType.Park,
    cost: 30,
    name: 'Praça',
    description: 'Aumenta a qualidade de vida e o verde',
    color: '#4ade80', 
    emoji: '🌳',
    popGen: 2,
    cookieGen: 0,
    unlockPop: 0,
    energyDelta: 0,
    satisfactionBonus: { type: 'environment', amount: 10 }
  },
  [BuildingType.WindTurbine]: {
    type: BuildingType.WindTurbine,
    cost: 100,
    name: 'Eólica',
    description: 'Energia limpa e sustentável (+8 Energia)',
    color: '#a3e635',
    emoji: '💨',
    popGen: 0,
    cookieGen: 5,
    unlockPop: 0,
    energyDelta: 8, 
    satisfactionBonus: { type: 'environment', amount: 5 }
  },
  [BuildingType.DataCenter]: {
    type: BuildingType.DataCenter,
    cost: 500,
    name: 'Data Center',
    description: 'Hub de tecnologia (+80 Cookies)',
    color: '#6366f1',
    emoji: '💾',
    popGen: 0,
    cookieGen: 80,
    unlockPop: 150,
    energyDelta: -15, 
  },
  [BuildingType.BeachResort]: {
    type: BuildingType.BeachResort,
    cost: 1000,
    name: 'Resort',
    description: 'Turismo de luxo na orla (+150 Cookies)',
    color: '#f472b6',
    emoji: '🏖️',
    popGen: 10,
    cookieGen: 150,
    unlockPop: 300,
    energyDelta: -10,
    satisfactionBonus: { type: 'leisure', amount: 15 }
  },
  [BuildingType.Metro]: {
    type: BuildingType.Metro,
    cost: 400,
    name: 'Metrô',
    description: 'Transporte rápido de massa (+20 Pop)',
    color: '#dc2626',
    emoji: '🚇',
    popGen: 20,
    cookieGen: 5,
    unlockPop: 200,
    energyDelta: -5,
    satisfactionBonus: { type: 'transport', amount: 10 }
  },
  [BuildingType.School]: {
    type: BuildingType.School,
    cost: 600,
    name: 'Escola',
    description: 'Educação Tech para o futuro (+Educação)',
    color: '#fb923c',
    emoji: '🏫',
    popGen: 5,
    cookieGen: 10,
    unlockPop: 100,
    energyDelta: -3,
    satisfactionBonus: { type: 'education', amount: 20 }
  },
  [BuildingType.Hospital]: {
    type: BuildingType.Hospital,
    cost: 800,
    name: 'Hospital',
    description: 'Serviços de saúde essenciais (+Saúde)',
    color: '#ffffff',
    emoji: '🏥',
    popGen: 30,
    cookieGen: 0,
    unlockPop: 150,
    energyDelta: -6,
    satisfactionBonus: { type: 'safety', amount: 20 }
  },
  [BuildingType.CityHall]: {
    type: BuildingType.CityHall,
    cost: 2000,
    name: 'Prefeitura',
    description: 'Centro administrativo. Habilita Leis.',
    color: '#e2e8f0',
    emoji: '🏛️',
    popGen: 5,
    cookieGen: 50,
    unlockPop: 250,
    energyDelta: -4,
    satisfactionBonus: { type: 'safety', amount: 10 }
  },
  [BuildingType.SolarFarm]: {
    type: BuildingType.SolarFarm,
    cost: 350,
    name: 'Solar',
    description: 'Alta geração de energia limpa (+15 Energia)',
    color: '#1e3a8a',
    emoji: '☀️',
    popGen: 0,
    cookieGen: 10,
    unlockPop: 80,
    energyDelta: 15, 
    satisfactionBonus: { type: 'environment', amount: 8 }
  },
};

/**
 * Lista expandida de melhorias (Upgrades) disponíveis para compra no ID Digital e nos Prédios.
 */
export const INITIAL_UPGRADES: Upgrade[] = [
   // 1. ZONA RESIDENCIAL (10 Upgrades)
  {
    id: 'res_1',
    name: 'Lâmpadas LED Econômicas',
    description: 'Reduz o custo de energia das residências.',
    cost: 100,
    targetType: BuildingType.Residential,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'res_2',
    name: 'Isolamento Térmico',
    description: 'Melhora o conforto e atrai mais moradores (+10% Pop).',
    cost: 250,
    targetType: BuildingType.Residential,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'res_3',
    name: 'Coleta Seletiva Smart',
    description: 'Lixeiras inteligentes melhoram a eficiência.',
    cost: 400,
    targetType: BuildingType.Residential,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'res_4',
    name: 'Internet Fibra Óptica',
    description: 'Conectividade básica para home office (+20% Renda).',
    cost: 600,
    targetType: BuildingType.Residential,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'res_5',
    name: 'Portaria Virtual',
    description: 'Segurança remota e redução de custos de condomínio.',
    cost: 800,
    targetType: BuildingType.Residential,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'res_6',
    name: 'Horta Comunitária',
    description: 'Alimentos frescos locais aumentam a satisfação.',
    cost: 1000,
    targetType: BuildingType.Residential,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'res_7',
    name: 'Painéis Solares de Telhado',
    description: 'Geração própria de energia alivia a rede.',
    cost: 1500,
    targetType: BuildingType.Residential,
    multiplier: 1.35,
    purchased: false,
  },
  {
    id: 'res_8',
    name: 'Automação IoT (Smart Home)',
    description: 'Casas totalmente conectadas (+40% Renda).',
    cost: 2500,
    targetType: BuildingType.Residential,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'res_9',
    name: 'Carregadores Veiculares',
    description: 'Infraestrutura para carros elétricos na garagem.',
    cost: 3500,
    targetType: BuildingType.Residential,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'res_10',
    name: 'Baterias Domésticas (Powerwall)',
    description: 'Armazenamento de energia para máxima eficiência.',
    cost: 5000,
    targetType: BuildingType.Residential,
    multiplier: 1.60,
    purchased: false,
  },

  // 2. COMÉRCIO
  {
    id: 'com_1',
    name: 'Máquina de Cartão Smart',
    description: 'Processamento de pagamentos mais rápido (+5% Renda).',
    cost: 150,
    targetType: BuildingType.Commercial,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'com_2',
    name: 'Wi-Fi Grátis para Clientes',
    description: 'Atrai mais visitantes para as lojas.',
    cost: 300,
    targetType: BuildingType.Commercial,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'com_3',
    name: 'Vitrine Holográfica',
    description: 'Anúncios 3D chamam muita atenção.',
    cost: 500,
    targetType: BuildingType.Commercial,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'com_4',
    name: 'Totem de Autoatendimento',
    description: 'Reduz filas e custos operacionais (+20% Renda).',
    cost: 750,
    targetType: BuildingType.Commercial,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'com_5',
    name: 'App de Fidelidade',
    description: 'Gamificação para manter clientes voltando.',
    cost: 1000,
    targetType: BuildingType.Commercial,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'com_6',
    name: 'Delivery por Drones',
    description: 'Entregas aéreas rápidas para toda a cidade.',
    cost: 1500,
    targetType: BuildingType.Commercial,
    multiplier: 1.35,
    purchased: false,
  },
  {
    id: 'com_7',
    name: 'Estoque Automatizado',
    description: 'Robôs organizam o almoxarifado.',
    cost: 2200,
    targetType: BuildingType.Commercial,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'com_8',
    name: 'Drive-Thru Inteligente',
    description: 'Reconhecimento de placa para pedidos instantâneos.',
    cost: 3000,
    targetType: BuildingType.Commercial,
    multiplier: 1.45,
    purchased: false,
  },
  {
    id: 'com_9',
    name: 'Marketing Preditivo IA',
    description: 'A IA sabe o que o cliente quer antes dele.',
    cost: 4500,
    targetType: BuildingType.Commercial,
    multiplier: 1.60,
    purchased: false,
  },
  {
    id: 'com_10',
    name: 'Robôs de Limpeza e Atendimento',
    description: 'Loja autônoma funcionando 24/7.',
    cost: 6000,
    targetType: BuildingType.Commercial,
    multiplier: 1.80,
    purchased: false,
  },

  // 3. INDÚSTRIA
  {
    id: 'ind_1',
    name: 'Correia Transportadora',
    description: 'Automação básica de linha de montagem.',
    cost: 300,
    targetType: BuildingType.Industrial,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'ind_2',
    name: 'Iluminação Industrial LED',
    description: 'Reduz custos fixos da fábrica.',
    cost: 500,
    targetType: BuildingType.Industrial,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'ind_3',
    name: 'Braços Robóticos',
    description: 'Substitui tarefas manuais repetitivas (+15% Produção).',
    cost: 800,
    targetType: BuildingType.Industrial,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'ind_4',
    name: 'Sensores de Monitoramento IoT',
    description: 'Evita paradas na produção com manutenção preditiva.',
    cost: 1200,
    targetType: BuildingType.Industrial,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'ind_5',
    name: 'Impressão 3D Industrial',
    description: 'Prototipagem e peças rápidas.',
    cost: 1800,
    targetType: BuildingType.Industrial,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'ind_6',
    name: 'Sistema de Reciclagem de Água',
    description: 'Fábrica mais sustentável e eficiente.',
    cost: 2500,
    targetType: BuildingType.Industrial,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'ind_7',
    name: 'Exoesqueletos para Operários',
    description: 'Aumenta a força e segurança dos trabalhadores.',
    cost: 3500,
    targetType: BuildingType.Industrial,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'ind_8',
    name: 'Logística Autônoma (AGVs)',
    description: 'Veículos guiados movem cargas sozinhos.',
    cost: 5000,
    targetType: BuildingType.Industrial,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'ind_9',
    name: 'Gêmeo Digital (Digital Twin)',
    description: 'Simulação completa da fábrica para otimização máxima.',
    cost: 7500,
    targetType: BuildingType.Industrial,
    multiplier: 1.70,
    purchased: false,
  },
  {
    id: 'ind_10',
    name: 'Manufatura Quântica',
    description: 'Precisão atômica na produção de chips e cookies.',
    cost: 10000,
    targetType: BuildingType.Industrial,
    multiplier: 2.00,
    purchased: false,
  },

  // 4. PARQUES
  {
    id: 'park_1',
    name: 'Bancos Confortáveis',
    description: 'Melhora o descanso dos visitantes.',
    cost: 50,
    targetType: BuildingType.Park,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'park_2',
    name: 'Iluminação Solar de Caminhos',
    description: 'Segurança e beleza à noite sem custo de energia.',
    cost: 100,
    targetType: BuildingType.Park,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'park_3',
    name: 'Lixeiras de Coleta Seletiva',
    description: 'Mantém o parque limpo automaticamente.',
    cost: 200,
    targetType: BuildingType.Park,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'park_4',
    name: 'Wi-Fi Público no Parque',
    description: 'Atrai jovens e nômades digitais.',
    cost: 350,
    targetType: BuildingType.Park,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'park_5',
    name: 'Academia ao Ar Livre',
    description: 'Equipamentos resistentes para saúde pública.',
    cost: 500,
    targetType: BuildingType.Park,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'park_6',
    name: 'Playground Moderno',
    description: 'Diversão segura para as crianças (+Satisfação).',
    cost: 750,
    targetType: BuildingType.Park,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'park_7',
    name: 'Bebedouros Inteligentes',
    description: 'Água filtrada e gelada monitorada.',
    cost: 1000,
    targetType: BuildingType.Park,
    multiplier: 1.35,
    purchased: false,
  },
  {
    id: 'park_8',
    name: 'Irrigação Automática',
    description: 'Sensores de umidade economizam água.',
    cost: 1500,
    targetType: BuildingType.Park,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'park_9',
    name: 'Palco de Eventos Holográfico',
    description: 'Shows e cultura sem montagem de palco.',
    cost: 2500,
    targetType: BuildingType.Park,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'park_10',
    name: 'Drones de Segurança e Limpeza',
    description: 'Parque 100% seguro e limpo 24h.',
    cost: 4000,
    targetType: BuildingType.Park,
    multiplier: 1.70,
    purchased: false,
  },

  // 5. HOSPITAL
  {
    id: 'hosp_1',
    name: 'Sistema de Senhas Digital',
    description: 'Organiza a fila de espera.',
    cost: 800,
    targetType: BuildingType.Hospital,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'hosp_2',
    name: 'Prontuário Eletrônico Unificado',
    description: 'Histórico do paciente acessível instantaneamente.',
    cost: 1200,
    targetType: BuildingType.Hospital,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'hosp_3',
    name: 'Equipamentos de Raio-X Digital',
    description: 'Diagnósticos mais rápidos e precisos.',
    cost: 1800,
    targetType: BuildingType.Hospital,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'hosp_4',
    name: 'Telemedicina',
    description: 'Consultas remotas para casos leves (+20% Capacidade).',
    cost: 2500,
    targetType: BuildingType.Hospital,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'hosp_5',
    name: 'Laboratório de Análises Automatizado',
    description: 'Resultados de exames em minutos, não dias.',
    cost: 3200,
    targetType: BuildingType.Hospital,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'hosp_6',
    name: 'Ambulâncias UTI Móvel',
    description: 'Atendimento crítico já no transporte.',
    cost: 4000,
    targetType: BuildingType.Hospital,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'hosp_7',
    name: 'Robô Cirurgião Assistente',
    description: 'Precisão milimétrica em cirurgias complexas.',
    cost: 5500,
    targetType: BuildingType.Hospital,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'hosp_8',
    name: 'Drones de Primeiros Socorros',
    description: 'Entrega desfibriladores antes da ambulância chegar.',
    cost: 7000,
    targetType: BuildingType.Hospital,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'hosp_9',
    name: 'Ala de Realidade Virtual (Reabilitação)',
    description: 'Fisioterapia gamificada e menos dolorosa.',
    cost: 9000,
    targetType: BuildingType.Hospital,
    multiplier: 1.60,
    purchased: false,
  },
  {
    id: 'hosp_10',
    name: 'Nanobots Medicinais',
    description: 'Cura acelerada a nível celular (Ficção Científica!).',
    cost: 12000,
    targetType: BuildingType.Hospital,
    multiplier: 2.00,
    purchased: false,
  },

  // 6. ESCOLA
  {
    id: 'sch_1',
    name: 'Tablets para Alunos',
    description: 'Substitui livros pesados por conteúdo digital.',
    cost: 600,
    targetType: BuildingType.School,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'sch_2',
    name: 'Lousas Interativas Digitais',
    description: 'Aulas mais dinâmicas e participativas.',
    cost: 1000,
    targetType: BuildingType.School,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'sch_3',
    name: 'Biblioteca Online (E-books)',
    description: 'Acesso ilimitado a conhecimento.',
    cost: 1500,
    targetType: BuildingType.School,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'sch_4',
    name: 'Laboratório de Robótica',
    description: 'Ensina lógica e engenharia desde cedo.',
    cost: 2200,
    targetType: BuildingType.School,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'sch_5',
    name: 'Aulas de Programação (Coding)',
    description: 'Prepara os jovens para o mercado da Gridline.',
    cost: 3000,
    targetType: BuildingType.School,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'sch_6',
    name: 'Merenda Orgânica e Nutritiva',
    description: 'Melhora a saúde e concentração dos alunos.',
    cost: 4000,
    targetType: BuildingType.School,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'sch_7',
    name: 'Realidade Aumentada (AR) na Sala',
    description: 'História e Geografia ganham vida.',
    cost: 5500,
    targetType: BuildingType.School,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'sch_8',
    name: 'Impressoras 3D Educacionais',
    description: 'Materializando ideias e projetos.',
    cost: 7000,
    targetType: BuildingType.School,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'sch_9',
    name: 'Campus Sustentável',
    description: 'Escola que gera sua própria energia e recicla.',
    cost: 9000,
    targetType: BuildingType.School,
    multiplier: 1.60,
    purchased: false,
  },
  {
    id: 'sch_10',
    name: 'IA Tutor Individual',
    description: 'Ensino personalizado para cada dificuldade do aluno.',
    cost: 12000,
    targetType: BuildingType.School,
    multiplier: 1.80,
    purchased: false,
  },

  // 7. ESTRADAS
  {
    id: 'road_1',
    name: 'Pintura Reflexiva',
    description: 'Melhora visibilidade noturna.',
    cost: 100,
    targetType: BuildingType.Road,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'road_2',
    name: 'Ciclovias Integradas',
    description: 'Incentiva transporte alternativo.',
    cost: 200,
    targetType: BuildingType.Road,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'road_3',
    name: 'Semáforos Inteligentes (IA)',
    description: 'Ajustam o tempo conforme o fluxo de carros.',
    cost: 400,
    targetType: BuildingType.Road,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'road_4',
    name: 'Asfalto Drenante',
    description: 'Evita poças e aquaplanagem na chuva.',
    cost: 600,
    targetType: BuildingType.Road,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'road_5',
    name: 'Radares de Velocidade',
    description: 'Aumenta a segurança no trânsito.',
    cost: 800,
    targetType: BuildingType.Road,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'road_6',
    name: 'Iluminação Pública LED Inteligente',
    description: 'Acende apenas quando há movimento.',
    cost: 1200,
    targetType: BuildingType.Road,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'road_7',
    name: 'Faixas Exclusivas de Ônibus',
    description: 'Prioriza o transporte público.',
    cost: 1800,
    targetType: BuildingType.Road,
    multiplier: 1.35,
    purchased: false,
  },
  {
    id: 'road_8',
    name: 'Sensores de Estacionamento',
    description: 'App mostra onde há vagas na rua.',
    cost: 2500,
    targetType: BuildingType.Road,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'road_9',
    name: 'Carregamento Sem Fio (Estrada)',
    description: 'Carrega carros elétricos em movimento (Experimental).',
    cost: 4000,
    targetType: BuildingType.Road,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'road_10',
    name: 'Túneis Subterrâneos Expressos',
    description: 'Desafoga o trânsito da superfície.',
    cost: 6000,
    targetType: BuildingType.Road,
    multiplier: 1.60,
    purchased: false,
  },

  // 8. METRÔ
  {
    id: 'metro_1',
    name: 'Bilhete Único Digital',
    description: 'Facilita o embarque e integração.',
    cost: 500,
    targetType: BuildingType.Metro,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'metro_2',
    name: 'Wi-Fi nos Vagões',
    description: 'Conforto para os passageiros.',
    cost: 800,
    targetType: BuildingType.Metro,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'metro_3',
    name: 'Ar Condicionado Eficiente',
    description: 'Ambiente climatizado com baixo consumo.',
    cost: 1200,
    targetType: BuildingType.Metro,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'metro_4',
    name: 'Portas de Plataforma Automáticas',
    description: 'Mais segurança nas estações.',
    cost: 1800,
    targetType: BuildingType.Metro,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'metro_5',
    name: 'Paineis Informativos em Tempo Real',
    description: 'Previsão exata de chegada dos trens.',
    cost: 2500,
    targetType: BuildingType.Metro,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'metro_6',
    name: 'Trens Autônomos (Driverless)',
    description: 'Maior frequência e precisão.',
    cost: 3500,
    targetType: BuildingType.Metro,
    multiplier: 1.35,
    purchased: false,
  },
  {
    id: 'metro_7',
    name: 'Sistema de Frenagem Regenerativa',
    description: 'Recupera energia nas paradas.',
    cost: 4500,
    targetType: BuildingType.Metro,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'metro_8',
    name: 'Vagões de Alta Capacidade',
    description: 'Transporta mais gente por viagem.',
    cost: 6000,
    targetType: BuildingType.Metro,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'metro_9',
    name: 'Segurança com Reconhecimento Facial',
    description: 'Monitoramento avançado das estações.',
    cost: 8000,
    targetType: BuildingType.Metro,
    multiplier: 1.60,
    purchased: false,
  },
  {
    id: 'metro_10',
    name: 'Levitação Magnética (MagLev)',
    description: 'Velocidade extrema e silêncio.',
    cost: 12000,
    targetType: BuildingType.Metro,
    multiplier: 2.00,
    purchased: false,
  },

  // 9. PREFEITURA
  {
    id: 'gov_1',
    name: 'Site da Prefeitura Responsivo',
    description: 'Acesso fácil aos serviços públicos.',
    cost: 2000,
    targetType: BuildingType.CityHall,
    multiplier: 1.05,
    purchased: false,
  },
  {
    id: 'gov_2',
    name: 'Digitalização de Documentos',
    description: 'Fim da papelada e carimbos.',
    cost: 2500,
    targetType: BuildingType.CityHall,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'gov_3',
    name: 'Portal da Transparência',
    description: 'Aumenta a confiança da população.',
    cost: 3000,
    targetType: BuildingType.CityHall,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'gov_4',
    name: 'Sistema de Alvará Automático',
    description: 'Acelera novas construções na cidade.',
    cost: 4000,
    targetType: BuildingType.CityHall,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'gov_5',
    name: 'Votação Eletrônica Segura',
    description: 'Consultas públicas rápidas.',
    cost: 5000,
    targetType: BuildingType.CityHall,
    multiplier: 1.25,
    purchased: false,
  },
  {
    id: 'gov_6',
    name: 'Big Data Urbano',
    description: 'Análise de dados para decisões melhores.',
    cost: 7000,
    targetType: BuildingType.CityHall,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'gov_7',
    name: 'Inteligência Artificial Tributária',
    description: 'Otimiza a arrecadação de Cookies (+Renda).',
    cost: 9000,
    targetType: BuildingType.CityHall,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'gov_8',
    name: 'Blockchain Governamental',
    description: 'Registros imutáveis e seguros.',
    cost: 12000,
    targetType: BuildingType.CityHall,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'gov_9',
    name: 'Centro de Operações Integradas',
    description: 'Polícia, bombeiros e trânsito na mesma sala.',
    cost: 15000,
    targetType: BuildingType.CityHall,
    multiplier: 1.60,
    purchased: false,
  },
  {
    id: 'gov_10',
    name: 'Prefeitura no Metaverso',
    description: 'Atendimento presencial 100% virtual.',
    cost: 20000,
    targetType: BuildingType.CityHall,
    multiplier: 1.80,
    purchased: false,
  },

  // 10. ENERGIA E TECH
  {
    id: 'tech_1',
    name: 'Cabos de Transmissão Eficientes',
    description: 'Menos perda de energia na rede.',
    cost: 500,
    targetType: BuildingType.WindTurbine, 
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'tech_2',
    name: 'Pás Aerodinâmicas Avançadas',
    description: 'Turbinas eólicas giram com menos vento.',
    cost: 1000,
    targetType: BuildingType.WindTurbine,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'tech_3',
    name: 'Rastreador Solar (Tracker)',
    description: 'Painéis seguem o sol durante o dia.',
    cost: 1000,
    targetType: BuildingType.SolarFarm,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'tech_4',
    name: 'Refrigeração Líquida (Data Center)',
    description: 'Reduz consumo de energia dos servidores.',
    cost: 1500,
    targetType: BuildingType.DataCenter,
    multiplier: 1.15,
    purchased: false,
  },
  {
    id: 'tech_5',
    name: 'Baterias de Lítio Industrial',
    description: 'Estabiliza a rede eólica.',
    cost: 2000,
    targetType: BuildingType.WindTurbine,
    multiplier: 1.30,
    purchased: false,
  },
  {
    id: 'tech_6',
    name: 'Células de Perovskita',
    description: 'Painéis solares de nova geração.',
    cost: 2500,
    targetType: BuildingType.SolarFarm,
    multiplier: 1.40,
    purchased: false,
  },
  {
    id: 'tech_7',
    name: 'Processadores Quânticos',
    description: 'Data Center processa 100x mais dados.',
    cost: 5000,
    targetType: BuildingType.DataCenter,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'tech_8',
    name: 'Rede Neural de Gestão',
    description: 'IA controla a distribuição de energia.',
    cost: 6000,
    targetType: BuildingType.SolarFarm,
    multiplier: 1.50,
    purchased: false,
  },
  {
    id: 'tech_9',
    name: 'Supercondutores',
    description: 'Transmissão de energia sem resistência.',
    cost: 8000,
    targetType: BuildingType.WindTurbine,
    multiplier: 1.60,
    purchased: false,
  },
  {
    id: 'tech_10',
    name: 'IA Generativa Dedicada',
    description: 'Data Center cria novos produtos sozinho.',
    cost: 10000,
    targetType: BuildingType.DataCenter,
    multiplier: 2.00,
    purchased: false,
  },
  // Beach Resort Extras
  {
    id: 'resort_1',
    name: 'Espreguiçadeiras Premium',
    description: 'Mais conforto na areia.',
    cost: 1500,
    targetType: BuildingType.BeachResort,
    multiplier: 1.10,
    purchased: false,
  },
  {
    id: 'resort_2',
    name: 'Bar Molhado',
    description: 'Drinks na piscina aumentam o consumo.',
    cost: 2500,
    targetType: BuildingType.BeachResort,
    multiplier: 1.20,
    purchased: false,
  },
  {
    id: 'resort_3',
    name: 'Spa de Luxo',
    description: 'Massagens e tratamentos caros.',
    cost: 4000,
    targetType: BuildingType.BeachResort,
    multiplier: 1.30,
    purchased: false,
  },
   {
    id: 'resort_4',
    name: 'Cassino Subterrâneo',
    description: 'Entretenimento adulto de alto nível.',
    cost: 8000,
    targetType: BuildingType.BeachResort,
    multiplier: 1.80,
    purchased: false,
  },
];

/**
 * Lista inicial de Ações na Bolsa de Valores.
 */
export const INITIAL_STOCKS: Stock[] = [
  {
    id: 's1',
    symbol: 'CRNCH',
    name: 'Cookie Crunch Ltda',
    description: 'Conglomerado de alimentos básicos.',
    price: 10,
    volatility: 0.02, 
    owned: 0,
    history: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  },
  {
    id: 's2',
    symbol: 'VOLT',
    name: 'Gridline Energia',
    description: 'Infraestrutura e energia renovável.',
    price: 50,
    volatility: 0.05, 
    owned: 0,
    history: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  },
  {
    id: 's3',
    symbol: 'NANO',
    name: 'NanoFuture Tech',
    description: 'Startups de alta tecnologia e IA.',
    price: 100,
    volatility: 0.15,
    owned: 0,
    history: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
  }
];

/**
 * Políticas Públicas disponíveis na Prefeitura.
 */
export const POLICIES: Policy[] = [
  {
    id: 'tax_break',
    name: 'Incentivo Fiscal Tecnológico',
    description: 'Reduz impostos para atrair empresas. Produção de Cookies +20%, mas custa 10 C$/tick.',
    costPerTick: 10,
    active: false,
    effect: { target: 'cookies', value: 1.2, type: 'multiplier' }
  },
  {
    id: 'green_city',
    name: 'Cidade Verde',
    description: 'Foco total em sustentabilidade. Satisfação +10, mas custa 15 C$/tick.',
    costPerTick: 15,
    active: false,
    effect: { target: 'satisfaction', value: 10, type: 'flat' }
  },
  {
    id: 'night_life',
    name: 'Vida Noturna Vibrante',
    description: 'Incentiva comércio 24h. Bônus de população +10%, Custo 5 C$/tick.',
    costPerTick: 5,
    active: false,
    effect: { target: 'population', value: 1.1, type: 'multiplier' }
  },
  {
    id: 'safety_first',
    name: 'Vigilância Inteligente',
    description: 'Câmeras e IA para segurança. Satisfação +5, Custo 8 C$/tick.',
    costPerTick: 8,
    active: false,
    effect: { target: 'satisfaction', value: 5, type: 'flat' }
  }
];
